version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test:
        - "CMD-SHELL"
        - "cub zk-ready localhost 2181"
      interval: 3s
      timeout: 10s
      retries: 30

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    restart: always
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_TRANSACTION_MAX_TIMEOUT_MS: 2400000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=broker -Dcom.sun.management.jmxremote.rmi.port=9997
    healthcheck:
      test:
        - "CMD-SHELL"
        - "cub kafka-ready -b kafka:29092 1 10"
      interval: 3s
      timeout: 10s
      retries: 30
    ports:
      - "9092:9092"
  akhq:
    image: tchiotludo/akhq:latest
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - "./akhq.yml:/app/application.yml"
    ports:
      - "8080:8080"
